name: my_imdb_stats
version: 0.0.1
description: Generate some statistics from the IMDb account

environment:
  sdk: '>=1.9.0 <2.0.0'
  
dependencies:
  browser: ^0.10.0
  polymer_elements: ^1.0.0-rc.8
  polymer: ^1.0.0-rc.15
  web_components: ^0.12.0
  chrome: any
  #async_await:
  #  git: git://github.com/dart-lang/async_await.git

transformers:
- chrome
#- async_await
- polymer:
    entry_points: web/index.html
- $dart2js:
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
#- $dart2js:
#    csp: true
